<template>

  <v-card elevation="24" rounded="xl" min-width="250" max-width="600" class="flip-scale-up-hor">
    <v-card-text class="text-center">
      <v-label class="text-center">Enter string</v-label>
      <v-text-field v-model="QRURL" label="Type data to encrypt"></v-text-field>
      <v-btn color="green" @click="generateQR()">Generar QR</v-btn>
      <v-img class="mt-8 mb-4 " v-model="imgQR" :src="imgQR"></v-img>
      <v-row justify="center" class="mt-4 mb-4" v-if="imgQR">
        <v-btn class="mr-2 ml-2" @click="dowloadImage()" rounded="xl" color="primary">Descargar</v-btn>
        <v-btn class="mr-2 ml-2" @click="reset()" rounded="xl" color="red">Reset</v-btn>
      </v-row>
    </v-card-text>
  </v-card>
</template>

<script setup>
import QRious from 'qrious';
import { saveAs } from 'file-saver';
import { ref } from 'vue';
const QRData = ref("")
const imgQR = ref(null);
const QRURL = ref("");

/*************************************************************** */
const generateQR = () => {
  const qr = new QRious({
          value: QRURL.value,
          background: 'white',
          backgroundAlpha: 0.8,
          foreground: 'black',
          foregroundAlpha: 0.8,
          level: 'H',
          padding: 25,
          size: 500,
        });
        QRData.value = qr;
        imgQR.value = qr.image;

};

const dowloadImage = async () => {
  const imagenData = QRData.value.toDataURL("image/png", 1.0)
          const image = new Image();
          image.src = imagenData;
          const imageData = imagenData.split(",")[1];
          const mimeType = "image/png";
          const fileName = "QRCode.png";
          const fileData = b64toBlob(imageData, mimeType);
          saveAs(fileData, fileName)
}

/**
 * The function converts a base64 encoded string to a Blob object.
 * @param b64Data - A base64 encoded string representing the data to be converted to a Blob object.
 * @param mimeType - The MIME type of the data being converted from base64 to a Blob object. Examples
 * of MIME types include "image/png", "application/pdf", "text/plain", etc.
 * @returns The function `b64toBlob` returns a Blob object.
 */
const b64toBlob = (b64Data, mimeType) => {
const byteCharacters = atob(b64Data);
  const byteArrays = [];
  for (let offset = 0; offset < byteCharacters.length; offset += 1024) {
    const slice = byteCharacters.slice(offset, offset + 1024);
    const byteNumbers = new Array(slice.length);
    for (let i = 0; i < slice.length; i++) {
      byteNumbers[i] = slice.charCodeAt(i);
    }
    const byteArray = new Uint8Array(byteNumbers);
    byteArrays.push(byteArray);
  }
  const blob = new Blob(byteArrays, { type: mimeType });
  return blob;
}

const reset = () => {
  QRData.value = "";
  imgQR.value = "";
  QRURL.value = "";
}
</script>
<style scoped>
.flip-scale-up-hor {
	-webkit-animation: flip-scale-up-hor 0.5s linear both;
  animation: flip-scale-up-hor 5s linear 10s infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2023-4-5 14:28:15
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-scale-up-hor
 * ----------------------------------------
 */
 @-webkit-keyframes flip-scale-up-hor {
  0% {
    -webkit-transform: scale(1) rotateX(0);
            transform: scale(1) rotateX(0);
  }
  50% {
    -webkit-transform: scale(2.5) rotateX(-90deg);
            transform: scale(2.5) rotateX(-90deg);
  }
  100% {
    -webkit-transform: scale(1) rotateX(-180deg);
            transform: scale(1) rotateX(-180deg);
  }
}
@keyframes flip-scale-up-hor {
  0% {
    -webkit-transform: scale(1) rotateX(0);
            transform: scale(1) rotateX(0);
  }
  50% {
    -webkit-transform: scale(2.5) rotateX(-90deg);
            transform: scale(2.5) rotateX(-90deg);
  }
  100% {
    -webkit-transform: scale(1) rotateX(-180deg);
            transform: scale(1) rotateX(-180deg);
  }
}

</style>
