<template>
	<router-view />
</template>

<script setup>
	import { onMounted } from 'vue'
	//
	import AOS from 'aos'
	import 'aos/dist/aos.css'
	onMounted(() => {
		AOS.init({
			// Opciones de configuración de AOS
		})
	})
</script>

<style>
	html {
		max-width: 1920px;
		margin: auto;
		scroll-behavior: smooth;
	}
	.text-focus-in {
		background: rgb(51, 45, 165);
		background: -webkit-linear-gradient(
			90deg,
			rgb(121, 118, 170) 18%,
			rgb(75, 75, 233) 51%,
			rgb(51, 191, 219) 100%
		);
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
		-webkit-animation: text-focus-in 2s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
		animation: text-focus-in 2s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
	}
	/* ----------------------------------------------
 * Generated by Animista on 2023-4-19 15:46:48
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

	/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
	@-webkit-keyframes text-focus-in {
		0% {
			-webkit-filter: blur(12px);
			filter: blur(12px);
			opacity: 0;
		}
		100% {
			-webkit-filter: blur(0px);
			filter: blur(0px);
			opacity: 1;
		}
	}
	@keyframes text-focus-in {
		0% {
			-webkit-filter: blur(12px);
			filter: blur(12px);
			opacity: 0;
		}
		100% {
			-webkit-filter: blur(0px);
			filter: blur(0px);
			opacity: 1;
		}
	}
	.fade-enter-active,
	.fade-leave-active {
		transition: opacity 0.5s;
	}

	.fade-enter,
	.fade-leave-to {
		opacity: 0;
	}
</style>
